### ISSUE TITLE
Cisco IOS supported?

### ISSUE THREAD

**Issue by dwydler** [ovh/the-bastion#254]
Hi Guys,
we use The Bastion in combination with Ansible via the Ansible Wrapper extension.  Not only for administration but also to distribute configurations (e.g. SNMP). This works fine in combination with Debian and Ubuntu Server. 

We are currently trying to do the same with Cisco Catalyst devices (IOS). We have set up a very simple example for testing.

This is our Inventory:
```
all:
  hosts:
    # Cisco IOS
    switch01:
      ansible_host: 192.168.0.1
      ansible_network_os: ios

children:
    switches:
      hosts:
        switch01:
```

This this our playbook:
```
---
- hosts: switches
  gather_facts: false
  connection: ansible.netcommon.network_cli

  tasks:
    - name: Run cli_command on Cisco IOS and display results
      block:
      - name: Run cli_command on Cisco IOS
        ansible.netcommon.cli_command:
          command: show ip int br
        register: result
```
This this our group_vars:
```
bastion_user: ansible
bastion_host: bastion.domain.com
bastion_port: 22

ansible_connection: network_cli
ansible_user: admin
ansible_network_os: ios
ansible_become: yes
ansible_become_method: enable

ansible_ssh_transfer_method: scp
ansible_ssh_pipelining: 1
ansible_ssh_executable: /home/ansible/AnsibleConfig/library/the-bastion/sshwrapper.py

ansible_scp_if_ssh: True
ansible_scp_executable: /home/ansible/AnsibleConfig/library/the-bastion/scpbastion.sh
```

This is our displayed error output:
```
354093 1634323654.86474: host switch01 is done iterating, returning The full traceback is:
  File "/tmp/ansible_ansible.netcommon.cli_command_payload_tb3lyzxx/ansible_ansible.netcommon.cli_command_payload.zip/ansible_collections/ansible/netcommon/plugins/modules/cli_command.py", line 170, in main
  File "/tmp/ansible_ansible.netcommon.cli_command_payload_tb3lyzxx/ansible_ansible.netcommon.cli_command_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [switch01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "answer": null,
            "check_all": false,
            "command": "show ip int br",
            "newline": true,
            "prompt": null,
            "sendonly": false
        }
    },
    "msg": "command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}
```
Ansible version:
```
ansible [core 2.11.6] 
  config file = /home/ansible/.ansible.cfg
  configured module search path = ['/home/ansible/AnsibleConfig/library']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

Can someone give me a push on what I'm doing wrong?
